url: "/"
baseurl: ""

# Site settings
title: WebApp.es
email: info@webapp.es
description: "Soluciones multimedia para cualquier tipo de negocio"


# Team names, titles and social links
people:
- name: Juan Miguel Rúa
  pic: 1
  position: Lead Architect
  social:
    - title: twitter
      url: https://twitter.com//@JuanMiguelRua
    - title: facebook
      url: https://www.facebook.com/juanmiguel.rua
    - title: stack-overflow
      url: https://stackoverflow.com/users/1809647/juanmiguelrua
    - title: linkedin
      url: https://www.linkedin.com/in/juan-miguel-r%C3%BAa-guti%C3%A9rrez-a4313754/

- name: Manel Perez Jutglar
  pic: 2
  position: Lead Architect
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 43820 Calafell
  - line: Tarragona, Spaña

# Build settings
markdown: kramdown
permalink: pretty
